# Generated by Django 3.1.6 on 2022-04-10 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='permissions',
            field=models.ManyToManyField(blank=True, default=None, related_name='folder_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
