# Generated by Django 3.1.6 on 2022-04-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileManage', '0002_auto_20220410_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='folder',
            name='files',
            field=models.ManyToManyField(blank=True, default=None, related_name='folder_files', to='fileManage.File'),
        ),
    ]
